CREATE TABLE `suppliers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `public_id` VARCHAR(36) NOT NULL,
  `supplier_no` VARCHAR(32) NOT NULL,
  `type` ENUM('FARMER','COOPERATIVE','PACKAGING_FACTORY','OTHER') NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `contact_name` VARCHAR(50) NULL,
  `phone` VARCHAR(24) NULL,
  `address` VARCHAR(255) NULL,
  `supply_categories` JSON NOT NULL,
  `settlement_terms` VARCHAR(500) NULL,
  `quality_grade` VARCHAR(32) NULL,
  `quality_score` TINYINT UNSIGNED NULL,
  `delivery_score` TINYINT UNSIGNED NULL,
  `quantity_accuracy_score` TINYINT UNSIGNED NULL,
  `after_sales_score` TINYINT UNSIGNED NULL,
  `price_stability_score` TINYINT UNSIGNED NULL,
  `attachment_object_keys` JSON NOT NULL,
  `status` ENUM('ACTIVE','DISABLED') NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  UNIQUE INDEX `suppliers_public_id_key` (`public_id`),
  UNIQUE INDEX `suppliers_supplier_no_key` (`supplier_no`),
  INDEX `suppliers_type_status_idx` (`type`,`status`),
  INDEX `suppliers_name_idx` (`name`),
  PRIMARY KEY (`id`),
  CONSTRAINT `suppliers_quality_score_check` CHECK (`quality_score` IS NULL OR `quality_score` BETWEEN 1 AND 5),
  CONSTRAINT `suppliers_delivery_score_check` CHECK (`delivery_score` IS NULL OR `delivery_score` BETWEEN 1 AND 5),
  CONSTRAINT `suppliers_quantity_accuracy_score_check` CHECK (`quantity_accuracy_score` IS NULL OR `quantity_accuracy_score` BETWEEN 1 AND 5),
  CONSTRAINT `suppliers_after_sales_score_check` CHECK (`after_sales_score` IS NULL OR `after_sales_score` BETWEEN 1 AND 5),
  CONSTRAINT `suppliers_price_stability_score_check` CHECK (`price_stability_score` IS NULL OR `price_stability_score` BETWEEN 1 AND 5)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
