CREATE TABLE `quality_inspections` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `public_id` VARCHAR(36) NOT NULL,
  `receipt_item_id` BIGINT NOT NULL,
  `inspector_admin_id` BIGINT NOT NULL,
  `idempotency_key` VARCHAR(128) NOT NULL,
  `request_hash` CHAR(64) NOT NULL,
  `sample_quantity` INT UNSIGNED NOT NULL,
  `accepted_quantity` INT UNSIGNED NOT NULL DEFAULT 0,
  `downgraded_quantity` INT UNSIGNED NOT NULL DEFAULT 0,
  `rejected_quantity` INT UNSIGNED NOT NULL DEFAULT 0,
  `appearance` VARCHAR(200) NULL,
  `size_observation` VARCHAR(200) NULL,
  `firmness` VARCHAR(200) NULL,
  `bloom` VARCHAR(200) NULL,
  `dryness` VARCHAR(200) NULL,
  `damage` VARCHAR(200) NULL,
  `mold` VARCHAR(200) NULL,
  `foreign_matter` VARCHAR(200) NULL,
  `odor` VARCHAR(200) NULL,
  `quality_grade` VARCHAR(32) NULL,
  `sample_image_object_keys` JSON NOT NULL,
  `conclusion` ENUM('PASS','DOWNGRADE','PARTIAL_REJECT','REJECT_ALL') NOT NULL,
  `note` VARCHAR(500) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `quality_inspections_public_id_key` (`public_id`),
  UNIQUE INDEX `quality_inspections_idempotency_key_key` (`idempotency_key`),
  INDEX `quality_inspections_receipt_item_id_created_at_idx` (`receipt_item_id`,`created_at`),
  INDEX `quality_inspections_inspector_admin_id_created_at_idx` (`inspector_admin_id`,`created_at`),
  PRIMARY KEY (`id`),
  CONSTRAINT `quality_inspections_receipt_item_id_fkey` FOREIGN KEY (`receipt_item_id`) REFERENCES `purchase_receipt_items` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `quality_inspections_inspector_admin_id_fkey` FOREIGN KEY (`inspector_admin_id`) REFERENCES `admin_users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `quality_inspections_quantity_check` CHECK (`sample_quantity` > 0 AND `accepted_quantity` + `downgraded_quantity` + `rejected_quantity` = `sample_quantity`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
