import{randomBytes}from'node:crypto';import{Prisma,type PrismaClient,type RefundOrder as DbRefund}from'@prisma/client';import type{RefundOrder,RefundRepository}from'./refund-service.js';
export class PrismaRefundRepository implements RefundRepository{
constructor(private readonly prisma:PrismaClient){}
async findApprovedAftersale(id:string){const row=await this.prisma.aftersale.findUnique({where:{publicId:id},include:{order:{include:{refundOrders:{where:{status:'SUCCEEDED'},select:{amountCent:true}}}}}});if(!row||row.status!=='APPROVED')return null;return{aftersaleId:row.publicId,orderId:row.order.publicId,paidAmountCent:row.order.paidAmountCent,refundedAmountCent:row.order.refundOrders.reduce((s,x)=>s+x.amountCent,0),type:row.type};}
async findByIdempotency(adminId:string,key:string,hash:string){const row=await this.prisma.refundOrder.findUnique({where:{idempotencyKey:key},include:{aftersale:true,order:true}});if(!row)return null;if(row.requestedByAdminId!==BigInt(adminId)||row.requestHash!==hash)throw new Error('Refund idempotency key reused with different request');return map(row);}
async claim(input:Parameters<RefundRepository['claim']>[0]){const old=await this.findByIdempotency(input.adminId,input.key,input.hash);if(old)return{refund:old,isNew:false};const row=await this.prisma.$transaction(async tx=>{const admin=await tx.adminUser.findUnique({where:{id:BigInt(input.adminId)}});if(!admin||admin.status!=='ACTIVE')throw new Error('Admin user unavailable');const after=await tx.aftersale.findUnique({where:{publicId:input.aftersaleId},include:{order:{include:{paymentOrders:{where:{status:'SUCCEEDED'},orderBy:{createdAt:'desc'},take:1},refundOrders:{where:{status:'SUCCEEDED'}}}}}});if(!after||after.status!=='APPROVED'||after.type==='RESHIP')throw new Error('Aftersale is not refundable');await tx.$queryRaw`SELECT id FROM orders WHERE id = ${after.orderId} FOR UPDATE`;const refunded=after.order.refundOrders.reduce((s,x)=>s+x.amountCent,0);if(refunded+input.amountCent>after.order.paidAmountCent)throw new Error('Refund amount exceeds paid amount');const payment=after.order.paymentOrders[0];if(!payment)throw new Error('Successful payment not found');return tx.refundOrder.create({data:{refundNo:`RF${randomBytes(16).toString('hex').toUpperCase()}`,orderId:after.orderId,aftersaleId:after.id,paymentOrderId:payment.id,requestedByAdminId:BigInt(input.adminId),provider:input.provider,amountCent:input.amountCent,reason:input.reason,idempotencyKey:input.key,requestHash:input.hash},include:{aftersale:true,order:true}});});return{refund:map(row),isNew:true};}
async markPending(id:string,pid:string){return map(await this.update(id,{status:'PENDING',providerRefundId:pid}));}async markFailed(id:string,reason:string){return map(await this.update(id,{status:'FAILED',failureReason:reason}));}async markUnknown(id:string,reason:string){return map(await this.update(id,{status:'UNKNOWN',failureReason:reason}));}
async complete(event:Parameters<RefundRepository['complete']>[0]){return map(await this.prisma.$transaction(async tx=>{const row=await tx.refundOrder.findFirst({where:{provider:event.provider,providerRefundId:event.providerRefundId},include:{aftersale:true,order:true}});if(!row)throw new Error('Refund order not found');const duplicate=await tx.refundTransaction.findUnique({where:{provider_eventId:{provider:event.provider,eventId:event.eventId}}});if(duplicate)return row;if(row.amountCent!==event.amountCent)throw new Error('Refund amount mismatch');await tx.refundTransaction.create({data:{refundOrderId:row.id,provider:event.provider,eventId:event.eventId,providerRefundId:event.providerRefundId,amountCent:event.amountCent,occurredAt:new Date(event.occurredAt)}});const updated=await tx.refundOrder.update({where:{id:row.id},data:{status:'SUCCEEDED',succeededAt:new Date(event.occurredAt)},include:{aftersale:true,order:true}});await tx.aftersale.update({where:{id:row.aftersaleId},data:{status:'RESOLVED',logs:{create:{fromStatus:row.aftersale.status,toStatus:'RESOLVED',operatorType:'SYSTEM',operatorId:0,note:'REFUND_SUCCEEDED'}}}});return updated;}));}
private update(id:string,data:Prisma.RefundOrderUpdateInput){return this.prisma.refundOrder.update({where:{publicId:id},data,include:{aftersale:true,order:true}});}}
function map(row:DbRefund&{aftersale:{publicId:string};order:{publicId:string}}):RefundOrder{return{id:row.publicId,refundNo:row.refundNo,aftersaleId:row.aftersale.publicId,orderId:row.order.publicId,provider:row.provider,status:row.status,amountCent:row.amountCent,reason:row.reason,providerRefundId:row.providerRefundId};}
